### PR TITLE
Improve speed by refactor pointInTriangle routine and other minor improvements

### PR DESCRIPTION
**Pull request by MaxGraey**

### CODE REVIEW

**Comment by mourner** [comment]
Thanks a lot for the PR! I just got back from vacation — will check it out this week!

**Comment by MaxGraey** [comment]
don't hurry up) I also celebrate May holidays, so I know how is it.

**Comment by MaxGraey** [comment]
@mourner may be you have some questions?

**Comment by mourner** [comment]
Sorry, didn't have a chance for a closer look yet but on my plate! Perhaps you could rebase the PR meanwhile for a cleaner commit history? Also, I'm surprised that things like `* 0.5` instead of `/ 2` or property caching makes a difference, since V8 should optimize things like this. Perhaps you could rebase in a way so that bigger-impact changes are separated from minor-impact one? We need to balance performance with clarity of code so some of the smaller changes may not be worth the price.

**Comment by MaxGraey** [comment]
@mourner Ok, I will rebase PR and split to big/small perf changes in my opinions.
About caching properties. I was discussed about it in the past and figure outing that performance boost varied by browser from version to version, but never worse. As regards ```a / 2``` vs ```a * 0.5``` it just style tip is pointing to exact float operation, not integer. Obviously that cannot any performance profit.

**Comment by mourner** [comment]
@MaxGraey sorry for the delay, there's a lot on my plate at the moment. Will try to get back to Earcut PRs next week.

**Comment by jfirebaugh** [comment]
As of V8 6.1.534.48, these changes seem to improve performance on simple polygons, but reduce it on complex ones:

752f27f86a59291a6544592d17383915137daaab:
```
typical OSM building (15 vertices): x 610,039 ops/sec ±1.18% (91 runs sampled)
dude shape (94 vertices): x 40,384 ops/sec ±1.56% (90 runs sampled)
dude shape with holes (104 vertices): x 33,312 ops/sec ±1.17% (88 runs sampled)
complex OSM water (2523 vertices): x 519 ops/sec ±0.77% (89 runs sampled)
```

28cb6c5dc5ebd3c9ed8b3337ed9f0a2246dd5eb8:
```
typical OSM building (15 vertices): x 655,060 ops/sec ±1.17% (88 runs sampled)
dude shape (94 vertices): x 37,886 ops/sec ±1.60% (90 runs sampled)
dude shape with holes (104 vertices): x 29,778 ops/sec ±1.61% (91 runs sampled)
complex OSM water (2523 vertices): x 474 ops/sec ±0.81% (90 runs sampled)
```

**Pull request closed without merging**
