### PR TITLE
Kosta/fix index creation (fix for #13)

### PR DESCRIPTION
**Pull request by Kosta-Github**
This is a potential fix for #13

### CODE REVIEW

**Comment by mourner** [comment]
Thanks! Looks good to me. I'll now check if we can avoid getting vertex length on each vertex twice, and calculate dimensionality once instead...

**Comment by Kosta-Github** [comment]
how about this?

**Comment by Kosta-Github** [comment]
you could also make the number of dimensions variable and not just limiting it to 2 and 3 by explicitly using `node.p.length` for `dim` and not clamp it to 3. then you could replace https://github.com/mapbox/earcut/blob/master/src/earcut.js#L170-L172 by `vertices.concat(node.p);`

**Comment by mourner** [comment]
`concat` produces a new array, so it's slow.
Looks good now. Do you think there are use cases that require more than 3 dimensions?

**Comment by Kosta-Github** [comment]
ah yeah, right about `concat`...

I could imagine to store additional data with each vertices, such as normals, colors, uv-coordinates for texture mapping, and then use interleaved buffer arrays for that data to render it with WebGL...

But leaving that out for now works for me. If/when I have a concrete use case for that I can create another PR...

**Comment by mourner** [comment]
Published in 1.4.0. Also fixed the code to work with any number of dimensions.

**Pull request merged**
